# General
random_seed: null #42  # if null, no random seed will be used

##### ALNS configurations #####
alns_iterations: 25_000  # 50_000
lower_bound_nr_of_removals: 4
upper_bound_nr_of_removals: 100
upper_bound_factor_nr_of_removals: 0.4

### Define active operators
use_neighbor_graph_removal_deterministic: false
use_neighbor_graph_removal_random: true
use_random_removal: true
use_random_route_removal: true
use_request_graph_removal: false
use_shaw_simplified_deterministic: false
use_shaw_simplified_random: true
use_worst_removal_deterministic: false
use_worst_removal_random: true

use_greedy_insert: true
use_nregret_2: true
use_nregret_3: true
use_nregret_4: false
use_nregret_5: false
use_nregret_6: false
regret_consider_all_possible_insertion_per_route: false  # default in Ropke C&OR ยง5.2.2 p. 2415: false
regret_sum_over_all_n_regret: true  # default in Ropke C&OR ยง5.2.2 p. 2415: true (e.g. only consider 4th - best or (4th - best) + (3rd - best) + (2nd - best))

### Destroy operators parameters
neighbor_graph_removal_exponent: 6
shaw_removal_exponent: 6
worst_removal_exponent: 3

# calculation
rounding_precision: 1     # number of decimal places
epsilon: 0.0001           # precision for double comparision
bigM_regret: 100_000      # must be greater than the largest possible regret