
# ALNS configurations
alns_iterations: 50_000   # TODO wie heißt das im Paper (Omega?)

# calculation
rounding_precision: 1     # number of decimal places
epsilon: 0.0001           # precision for double comparision
bigM_regret: 100_000      # must be greater than the largest possible regret