##### General configurations #####
random_seed: null  # if null, no random seed will be used

##### ALNS configurations #####
alns_iterations: 25_000  # 50_000
# Upper bound and lower bound values taken from Ropke C&OR ยง6.1.1 p. 2417
lower_bound_nr_of_removals: 30
lower_bound_factor_nr_of_removals: 0.1
upper_bound_nr_of_removals: 60
upper_bound_factor_nr_of_removals: 0.4

cost_factor_unserved_customer: 5.0  # cost for unserviced customers is equal to this number times the maximum distance in the graph

### Define active operators (destroy and repair)
use_cluster_removal_kruskal: true
use_historic_node_pair_removal_deterministic: false
use_historic_node_pair_removal_random: true
use_historic_request_pair_removal: false
use_random_removal: true
use_random_route_removal: true
use_shaw_simplified_deterministic: false
use_shaw_simplified_random: true
use_time_oriented_removal_jungwirth_deterministic: false
use_time_oriented_removal_jungwirth_random: true
use_time_oriented_removal_pisinger_deterministic: false
use_time_oriented_removal_pisinger_random: true
use_worst_removal_deterministic: false
use_worst_removal_random: true

use_greedy_insert: true
use_nregret_2: true
use_nregret_3: true
use_nregret_4: false
use_nregret_5: false
use_nregret_6: false
regret_consider_all_possible_insertion_per_route: false  # default in Pisinger & Ropke C&OR ยง5.2.2 p. 2415: false
regret_sum_over_all_n_regret: true  # default in Ropke C&OR ยง5.2.2 p. 2415: true (e.g. only consider 4th - best or (4th - best) + (3rd - best) + (2nd - best))

### Destroy operators parameters
neighbor_graph_removal_exponent: 6
shaw_removal_exponent: 6
time_oriented_removal_exponent: 6  # in Pisinger & Ropke C&OR ยง5.1.5 p. 2414: identical to shaw_removal_exponent
time_oriented_nr_of_closest: 100  # maximum number of closest customers to consider when applying time oriented removal
time_oriented_jungwirth_weight_start_time_in_solution: .75  # alpha_1 in Jungwirth et al. 2021
worst_removal_exponent: 3

##### calculations #####
rounding_precision: 1     # number of decimal places
epsilon: 0.0001           # precision for double comparision
bigM_regret: 100_000      # must be greater than the largest possible regret


##### not defined in papers (open) #####
# - penalty for unserved customers ($\Gamma$)
# - time-oriented destroy. number of geographically close nodes ($B$) oder sind das auch die 100 Kunden?
# - score weights for all time score and score in last M iterations