# General
random_seed: 42  # if null, no random seed will be used

##### ALNS configurations #####
alns_iterations: 25_000  # 50_000
lower_bound_nr_of_removals: 4
upper_bound_nr_of_removals: 100
upper_bound_factor_nr_of_removals: 0.4

### Destroy operators
worst_removal_exponent: 3

# calculation
rounding_precision: 1     # number of decimal places
epsilon: 0.0001           # precision for double comparision
bigM_regret: 100_000      # must be greater than the largest possible regret